DRAFT - DO NOT MERGE
vaticle/biograkn-covid pull request #31
Opened 2023-07-04 15:13 UTC by james-whiteside

draft - do not merge

2023-07-12 11:33 UTC, james-whiteside commented
Still to do:
- Update readme.
- Fix broken test.

2023-07-13 10:31 UTC, SullivanDaly requested changes
As you will see, I have only two "issues" to report
- find a better place for constants
- trying to use title for rows instead of indexes

On a minor note (not requiering changes from my POV):
- Usage of single quotes to delimit string value to avoid escaping double quotes
- Placement of roleplayers in your tql schema, we should discuss what we want to display as best pratice.

2023-07-13 10:31 UTC, SullivanDaly commented on loader.py
> +# Set a max constant to 0 to migrate no entries.
Are those one meant to be changed from one execution to another?
If yes, putting them in a "properties" file may be a better approach?

2023-07-13 10:31 UTC, SullivanDaly commented on loader/coronavirus/coronavirus_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/coronavirus/coronavirus_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/dgidb/dgidb_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/dgidb/dgidb_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/disgenet/disgenet_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/hpa/hpa_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/reactome/reactome_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/tissuenet/tissuenet_loader.py
> +                interaction = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 10:31 UTC, SullivanDaly commented on loader/uniprot/uniprot_loader.py
> +        data = {
read_tsv has "header=True", so I think you can call rows with their name rather than indexes.

2023-07-13 17:20 UTC, james-whiteside commented on loader.py
> +# Set a max constant to 0 to migrate no entries.
Agreed, will change.

2023-07-13 17:21 UTC, james-whiteside commented on loader/coronavirus/coronavirus_loader.py
> +        data = {
Agreed, will change.

2023-07-14 11:26 UTC, SullivanDaly approved these changes
All good, ready for Merge :)

2023-07-14 14:24 UTC, merged